version: 2
sphinx:
  configuration: docs/conf.py
build:
  os: ubuntu-22.04
  tools:
    python: {{ cookiecutter.python_version }}
python:
  install:
    - method: pip
      path: .
      extra_requirements: [ docs ]
